#!/bin/sh

CFGFILE="/tmp/flash/avahi-daemon/avahi_service"

if [ ! -f $CFGFILE ]
then cat << EOF
<?xml version="1.0" standalone='no'?><!--*-nxml-*-->
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<service-group>

<name replace-wildcards="yes">%h</name>

<service>
<type>_afpovertcp._tcp</type>
<port>548</port>
</service>

</service-group>
EOF
else cat $CFGFILE;
fi
